openapi: 3.0.2
info:
  title: SIO API
  version: "1.0"
  description: 'Spécifications de l''API FILrouge'
  termsOfService: https://www.centralesupelec.fr
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Lien vers l'avancée du projet
  url: /projet
servers:
  - url: http://localhost:10000/api
tags:
  - name: fichier
    description: Conversion de fichiers en Json
  - name: hello
    description: fonction de test
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /fichier/:
    post:
      tags:
        - fichier
      summary: Depose un fichier et le traduit en Json
      description: Envoi limité à 10Mo par fichier. Le fichier sera traduit en JSON, en fonction de son type, puis stocké et retourné à l'envoyeur. Il contiendra des données de base sur le type de fichier, mais également des meta-donnees propres au type, et les donnees brutes du fichier. Si c'est un YAML, les donnees brutes seront transformées en pur JSON. Si c'est une Image, les donnees seront retournees en matrice RVB...
      operationId: controllers.fichier_ctrl.fichier_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                  format: base64
      responses:
        '201':
          description: Fichier converti avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fichier'
          links:
            GetFichier:
              operationId: controllers.fichier_ctrl.fichier_get
              parameters:
                idFichier: 'idFichier'
              description: >
                The `id` value returned in the response can be used as
                the `idFichier` parameter in `GET /fichier/{idFichier}`.
        '500':
          description: Erreur à la conversion
  '/fichier/{idFichier}':
    get:
      tags:
        - fichier
      summary: retrouver un fichier précédemment uploadé
      description: renvoi un fichier json d'un fichier déjà enregistré sur le serveur
      operationId: controllers.fichier_ctrl.fichier_get
      parameters:
        - name: idFichier
          in: path
          description: ID du json à retourner
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fichier retrouvé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fichier'
        '400':
          description: Invalide ID
        '404':
          description: Fichier non trouvé
    delete:
      tags:
        - fichier
      summary: retrouver un fichier précédemment uploadé et le supprimer
      description: renvoi un fichier json d'un fichier déjà enregistré sur le serveur. Il s'agira du dernier envoi du fichier au format JSON
      operationId: controllers.fichier_ctrl.fichier_delete
      parameters:
        - name: idFichier
          in: path
          description: ID du json à retourner et supprimer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fichier retrouvé et supprimé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fichier'
        '400':
          description: Invalide ID
        '404':
          description: Fichier non trouvé
  /hello/{name}:
    post:
      tags:
        - hello
      summary: hello world de test
      description: hello world de test
      operationId: controllers.hello_ctrl.hello
      responses:
        200:
          description: Dit bonjour
          content:
            text/plain:
              schema:
                type: string
                example: "Hello World!"
      parameters:
        - name: name
          in: path
          description: Nom de la personne à qui dire bonjour
          required: true
          schema:
            type: string
            example: "World"
components:
  schemas:
    Fichier:
      type: object
      properties:
#donnees communes à chaque fichier
        idFic:
          type: string
          example: 6cef510edf046c94085eeb6b2505b3ed
        nomFic:
          type: string
          example: image2019.jpg
        mimeType:
          type: string
          example: image/jpeg
        taille:
          type: integer
          example: 4111982
        extension:
          type: string
          example: jpg
        dateConversion:
          type: string
          format: date-time
#particularite à chaque fichier
        metaDonnees:
          type: object
          additionalProperties: {}
        donnees:
          type: object
          additionalProperties: {}
        hateOas:
          type: object
          properties:
            method:
              type: string
            url:
              type: string
            urn:
              type: string
