openapi: 3.0.2
info:
  title: SIO API
  version: "1.0"
  description: 'Spécifications de l''API FILrouge'
  termsOfService: https://www.centralesupelec.fr
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Lien vers l'avancée du projet
  url: /projet
servers:
  - url: http://localhost:10000/api
tags:
  - name: convertisseur
    description: Conversion de fichiers en Json
  - name: hello
    description: fonction de test
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /convert/:
    post:
      tags:
        - convertisseur
      summary: upload a file
      description: ''
      operationId: controllers.convert_ctrl.convert_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                  format: base64
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  adresseip:
                    type: string
                  mimetype:
                    type: string
                  data:
                    type: string
  /hello/{name}:
    post:
      tags:
        - hello
      summary: hello world de test
      description: hello world de test
      operationId: controllers.hello_ctrl.hello
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello Benoît!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "dave"
